#server:
#  port: 8080
#
#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2019/02/27
#  maps:{k1: v1,k2: 12}
#  lists:
#     - list
#     - zhaoliu
#  dog:
#    name: 小狗
#    age: 3
#  last-name: zhangsan
